# This is a basic workflow to help you get started with Actions

name: '000057-StartingWithAmazonS3-Upload'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  uploadS3:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          curl -o S3-Website-main.zip -L https://github.com/AWS-First-Cloud-Journey/S3-Website/archive/refs/heads/main.zip 
          unzip S3-Website-main.zip

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1      
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: us-east-2
          role-session-name: GitHubActions

      # Runs a single command using the runners shell
      - name: Deploy to S3
        run: |
          aws s3 cp ${{ github.workspace }}/S3-Website-main s3://${{ vars.S3_BUCKET_NAME }} --recursive